version: '3.8'

services:
  backend:
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    tty: true
    depends_on:
      - db
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nestjs-graphql-prac
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 33306:3306
    restart: always
    volumes:
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
